### ISSUE TITLE
Wrong assignment

### ISSUE THREAD

**Issue by icapathos** [maruel/temperature#1]
I read your "Go" code to convert to Python, and found out a miss.
At line 434,
`tR, tB, _ := ToRGB(floatToUint16(temperature))`
I must be changed as below
`tR, _, tB := ToRGB(floatToUint16(temperature))`

Best,
Hyungeun

**Comment by maruel** [comment]
Thanks a lot! Indeed, it was completely broken. Added a unit test so there's known data to compare against.
